#!/usr/bin/env bash

# The Bash script to display information on subdomains

# Checking if at least one argument is provided
if (( $# < 1 )); then
  echo "Usage: ${0} domain [subdomain1 subdomain2...]"
  exit 1
fi

# Setting the domain name
domain="${1}"

# Setting the default subdomains to query
declare -a subdomains=("www" "lb-01" "web-01" "web-02")

# If the additional subdomains are provided as arguments, adding to the subdomains array
if (( $# > 1 )); then
  subdomains+=("${@:2}")
fi

# Looping through the subdomains and displaying information
for subdomain in "${subdomains[@]}"; do
  output=$(dig "${subdomain}.${domain}" +short)
  if [[ -n ${output} ]]; then
    printf "The subdomain %s has IP address %s\n" "${subdomain}" "${output}"
  else
    printf "The subdomain %s does not exist\n" "${subdomain}"
  fi
done
