#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
/etc/init.d/nginx start
