#!/usr/bin/env bash
# configuring a new ubuntu machine
# Installing Nginx with a server 0x01 config
#+ add HTTP header named X-Served-By $HOSTNAME

apt-get update
apt-get install -y nginx

custom_header='http {\
	add_header X-Served-By \$HOSTNAME;'
file='/etc/nginx/nginx.conf'

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo sed -i s@'http {'@"$custom_header"@g "$file"
sudo service nginx restart
