#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# Open the 80 port

rm /etc/nginx/sites-enabled/default

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart

