#!/usr/bin/env bash
#the nginx server configuration, on port 80

# removing the default nginx file configuration
rm /etc/nginx/sites-enabled/default
# the nginx configuration listens on the port 80 for ll IPV4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# nginx start
service nginx restart
