#!/usr/bin/env bash
# Opening the 80 port, configuring the Nginx server

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
