#!/usr/bin/env bash
# Sript to display to infinity and beyond indefinitely, and 'I am invincible!!!' when receiving a SIGTERM

for (( k=1; k>0; k++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
