#!/usr/bin/env bash
# Print Best School 10 times using the While Loop
# but in the ninth iteration it will display Best School and Hi

k=1
while [ $k -le 10 ]
do
    echo "Best School"
    if [ "$k" -eq 9 ]
    then
	echo "Hi"
    fi

    ((k++))
done
