#!/usr/bin/env bash
# an  ash script to display numbers 1 to 20 and:
# displays 4 then bad luck from China for fourth loop iteration
# displays 9 and then bad luck from Japan for ninth loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

k=1
while [ $k -le 20 ]
do

    case $k in

    4)
	echo "$k"
	echo "bad luck from China"
	;;
    9)
	echo "$k"
        echo "bad luck from Japan"
	;;
    17)
	echo "$k"
        echo "bad luck from Italy"
	;;
    *)
        echo "$k"
	;;
    esac
    ((k++))
done
