#!/usr/bin/env bash
# Script that configures an Ubuntu server
# Check if the script is run with root privileges

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Define the new IP addresses
NEW_LOCALHOST_IP="127.0.0.2"
NEW_FACEBOOK_IP="8.8.8.8"

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Modify the hosts file
sed -i "s/^127.0.0.1[[:space:]]*localhost$/127.0.0.1 localhost\n${NEW_LOCALHOST_IP} localhost/g" /etc/hosts
sed -i "s/^.*facebook.com[[:space:]]*$/127.0.0.1 facebook.com\n${NEW_FACEBOOK_IP} facebook.com/g" /etc/hosts

echo "Configuration complete. Changes applied."

# Check if Docker is running and restart it to apply changes
if systemctl is-active --quiet docker; then
    echo "Docker is running. Restarting Docker to apply changes."
    systemctl restart docker
fi
